name: dota2-ml
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  
  # Data Science Core
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.11.0
  
  # Machine Learning
  - scikit-learn>=1.3.0
  - joblib>=1.3.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Development
  - jupyter>=1.0.0
  - pip
  
  # Optional: Uncomment for parquet support
  - pyarrow>=12.0.0
  
  # Pip dependencies
  - pip:
    - plotly>=5.15.0
    - tqdm>=4.65.0
    - xgboost>=1.7.0
    - lightgbm>=4.0.0
    
    # Optional pip packages (uncomment if needed)
    # - fastparquet>=2023.7.0