name: dota-ml
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python + Scientific Stack (conda excels here)
  - python=3.11
  - numpy>=1.24.0        # conda version has Intel MKL optimization
  - pandas>=2.0.0        # conda version is faster
  - scipy>=1.11.0        # optimized BLAS libraries
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  
  # ML packages that work well with conda
  - scikit-learn>=1.3.0  # conda version has optimizations
  - joblib>=1.3.0
  - pyarrow>=12.0.0      # better conda integration
  
  # Development tools
  - pip
  
  # Pip dependencies (for packages better/only available via pip)
  - pip:
    # PyTorch ecosystem (official recommendation)
    - torch>=2.4.0 --index-url https://download.pytorch.org/whl/cu126
    - torchvision>=0.19.0 --index-url https://download.pytorch.org/whl/cu126  
    - torchaudio>=2.4.0 --index-url https://download.pytorch.org/whl/cu126
    
    # ML packages better via pip
    - xgboost>=1.7.0       # often more up-to-date on pip
    - lightgbm>=4.0.0      # same
    
    # Visualization
    - plotly>=5.15.0       # better pip support
    - tqdm>=4.65.0         # simple, works everywhere